data_path:
    train_data: C:/Rakesh/GreyAtom/Deployment/Document_Summarizer/data/Train/Article1.txt
    test_data: C:/Rakesh/GreyAtom/Deployment/Document_Summarizer/data/Test/Article1.txt
sentence_num: 3